language: java

notifications:
  email:
    - tgvaughan@gmail.com

before_install:
  - "export DISPLAY=:0.0"
  - "sh -e /etc/init.d/xvfb start"

script: "export DISPLAY=:0.0" ant clean compile-all junitb
